// <auto-generated />
using System;
using HotelManager.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelManager.Infrastructure.Migrations.Sqlite
{
    [DbContext(typeof(HotelDbContext))]
    partial class HotelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("HotelManager.Domain.Entities.AdvanceEntry", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Deduction")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmployeeID")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("WorkingDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("AdvanceEntry", (string)null);
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.Appointment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllDay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Label")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecurrenceInfo")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceID")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subject")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Appointment", (string)null);
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.Beer", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("BeerName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Rate")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Beer", (string)null);
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.CheckInRoom", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Balance")
                        .HasColumnType("REAL");

                    b.Property<int?>("CurrencyID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateIN")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOUT")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Discount")
                        .HasColumnType("REAL");

                    b.Property<double?>("DiscountPer")
                        .HasColumnType("REAL");

                    b.Property<string>("ExtraBed")
                        .HasColumnType("TEXT");

                    b.Property<double?>("GrandTotal")
                        .HasColumnType("REAL");

                    b.Property<string>("GuestID")
                        .HasColumnType("TEXT");

                    b.Property<double?>("LuxuryTaxAmount")
                        .HasColumnType("REAL");

                    b.Property<double?>("LuxuryTaxPer")
                        .HasColumnType("REAL");

                    b.Property<int?>("NoOfAdults")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NoOfDays")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NoOfKids")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<double?>("OtherCharges")
                        .HasColumnType("REAL");

                    b.Property<int?>("RoomCharges")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoomNo")
                        .HasColumnType("TEXT");

                    b.Property<double?>("ServiceTaxAmount")
                        .HasColumnType("REAL");

                    b.Property<double?>("ServiceTaxPer")
                        .HasColumnType("REAL");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<double?>("SubTotal")
                        .HasColumnType("REAL");

                    b.Property<double?>("TotalPaid")
                        .HasColumnType("REAL");

                    b.Property<double?>("TotalRoomCharges")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.HasIndex("CurrencyID");

                    b.HasIndex("GuestID");

                    b.HasIndex("RoomNo");

                    b.ToTable("CheckIN_Room", (string)null);
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.CheckoutRoom", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BillNo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CheckInID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CheckOutDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CurrencyID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HotelID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("CheckInID");

                    b.HasIndex("CurrencyID");

                    b.HasIndex("HotelID");

                    b.ToTable("Checkout_Room", (string)null);
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.CurrencySet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CS_Currency")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("CurrencySet", (string)null);
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.Dish", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("DishName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Rate")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Dish", (string)null);
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.EmployeeAttendance", b =>
                {
                    b.Property<int>("AttendanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BasicWorkingTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeID")
                        .HasColumnType("TEXT");

                    b.Property<string>("InTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Overtime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("WorkingDate")
                        .HasColumnType("TEXT");

                    b.HasKey("AttendanceID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("EmployeeAttendance", (string)null);
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.EmployeePayment", b =>
                {
                    b.Property<string>("PaymentID")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Advance")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateTo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Deduction")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmployeeID")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModeOfPayment")
                        .HasColumnType("TEXT");

                    b.Property<int?>("NetPay")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OverTimeAmount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Overtime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OvertimeRate")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentModeDetails")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PresentDays")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Salary")
                        .HasColumnType("INTEGER");

                    b.HasKey("PaymentID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("EmployeePayment", (string)null);
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.EmployeeRegistration", b =>
                {
                    b.Property<string>("EmployeeID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("BasicWorkingTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bloodgroup")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfJoining")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .HasColumnType("TEXT");

                    b.Property<string>("Designation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MobileNo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Salary")
                        .HasColumnType("INTEGER");

                    b.HasKey("EmployeeID");

                    b.ToTable("EmployeeRegistration", (string)null);
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.ExtraBed", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Charges")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("ExtraBed", (string)null);
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.Garden", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Charges")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Garden", (string)null);
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.Guest", b =>
                {
                    b.Property<string>("GuestID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("GuestName")
                        .HasColumnType("TEXT");

                    b.Property<string>("IDNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("IDType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("GuestID");

                    b.ToTable("Guest", (string)null);
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.Hall", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Charges")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HallName")
                        .HasColumnType("TEXT")
                        .HasColumnName("Hall Name");

                    b.HasKey("ID");

                    b.ToTable("Hall", (string)null);
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.HotelInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactNo1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("HotelName")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Logo")
                        .HasColumnType("BLOB");

                    b.Property<string>("STNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("TIN")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("HotelInfo", (string)null);
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.Liquor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LiquorName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Rate")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Volume")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("LiquorName");

                    b.ToTable("Liquor", (string)null);
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.LiquorMaster", b =>
                {
                    b.Property<string>("LiquorName")
                        .HasColumnType("TEXT");

                    b.HasKey("LiquorName");

                    b.ToTable("Liquor_master", (string)null);
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.OrderInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CheckInID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CurrencyID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GrandTotal")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HotelID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderNo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PaymentDue")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("STAmount")
                        .HasColumnType("REAL");

                    b.Property<double?>("STPer")
                        .HasColumnType("REAL");

                    b.Property<int?>("SubTotal")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TotalPayment")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("VATAmount")
                        .HasColumnType("REAL");

                    b.Property<double?>("VATPer")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.HasIndex("CheckInID");

                    b.HasIndex("CurrencyID");

                    b.HasIndex("HotelID");

                    b.ToTable("Order_Info", (string)null);
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.OrderedProduct", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrderID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductID")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Rate")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Volume")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("OrderID");

                    b.ToTable("OrderedProduct", (string)null);
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.PurchasedInventory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("PartyName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Quantity")
                        .HasColumnType("REAL");

                    b.Property<int?>("TotalPrice")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransactionType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("PurchasedInventory", (string)null);
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.Registration", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("JoiningDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameOfuser")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserType")
                        .HasColumnType("TEXT");

                    b.Property<string>("User_Password")
                        .HasColumnType("TEXT");

                    b.HasKey("UserName");

                    b.ToTable("Registration", (string)null);
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.Reservation", b =>
                {
                    b.Property<string>("ReservationID")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateIN")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOUT")
                        .HasColumnType("TEXT");

                    b.Property<string>("GuestID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("ReservationID");

                    b.HasIndex("GuestID");

                    b.HasIndex("RoomNo");

                    b.ToTable("Reservation", (string)null);
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.ReservationHallAndGarden", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Balance")
                        .HasColumnType("REAL");

                    b.Property<int?>("CurrencyID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateFrom_Garden")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateFrom_Hall")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateTo_Garden")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateTo_Hall")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Days_Garden")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Days_Hall")
                        .HasColumnType("REAL");

                    b.Property<double?>("Discount")
                        .HasColumnType("REAL");

                    b.Property<double?>("DiscountPer")
                        .HasColumnType("REAL");

                    b.Property<string>("Garden")
                        .HasColumnType("TEXT");

                    b.Property<double?>("GrandTotal")
                        .HasColumnType("REAL");

                    b.Property<string>("GuestID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hall")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HotelID")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("LuxuryTaxAmount")
                        .HasColumnType("REAL");

                    b.Property<double?>("LuxuryTaxPer")
                        .HasColumnType("REAL");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<double?>("OtherCharges")
                        .HasColumnType("REAL");

                    b.Property<double?>("Rate_Garden")
                        .HasColumnType("REAL");

                    b.Property<double?>("Rate_Hall")
                        .HasColumnType("REAL");

                    b.Property<double?>("ServiceTaxAmount")
                        .HasColumnType("REAL");

                    b.Property<double?>("ServiceTaxPer")
                        .HasColumnType("REAL");

                    b.Property<double?>("SubTotal")
                        .HasColumnType("REAL");

                    b.Property<double?>("TotalCharges_Garden")
                        .HasColumnType("REAL");

                    b.Property<double?>("TotalCharges_Hall")
                        .HasColumnType("REAL");

                    b.Property<double?>("TotalPaid")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.HasIndex("CurrencyID");

                    b.HasIndex("GuestID");

                    b.HasIndex("HotelID");

                    b.ToTable("Reservation_HallandGarden", (string)null);
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.ReservationHallOrGarden", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Balance")
                        .HasColumnType("REAL");

                    b.Property<int?>("CurrencyID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateTo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Days")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Discount")
                        .HasColumnType("REAL");

                    b.Property<double?>("DiscountPer")
                        .HasColumnType("REAL");

                    b.Property<double?>("GrandTotal")
                        .HasColumnType("REAL");

                    b.Property<string>("GuestID")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HotelID")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("LuxuryTaxAmount")
                        .HasColumnType("REAL");

                    b.Property<double?>("LuxuryTaxPer")
                        .HasColumnType("REAL");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<double?>("OtherCharges")
                        .HasColumnType("REAL");

                    b.Property<double?>("Rate")
                        .HasColumnType("REAL");

                    b.Property<double?>("ServiceTaxAmount")
                        .HasColumnType("REAL");

                    b.Property<double?>("ServiceTaxPer")
                        .HasColumnType("REAL");

                    b.Property<double?>("SubTotal")
                        .HasColumnType("REAL");

                    b.Property<double?>("TotalCharges")
                        .HasColumnType("REAL");

                    b.Property<double?>("TotalPaid")
                        .HasColumnType("REAL");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("CurrencyID");

                    b.HasIndex("GuestID");

                    b.HasIndex("HotelID");

                    b.ToTable("Reservation_HallorGarden", (string)null);
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.RestaurantOrderInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CurrencyID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GrandTotal")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HotelID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderNo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PaymentDue")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("STAmount")
                        .HasColumnType("REAL");

                    b.Property<double?>("STPer")
                        .HasColumnType("REAL");

                    b.Property<int?>("SubTotal")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TotalPayment")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("VATAmount")
                        .HasColumnType("REAL");

                    b.Property<double?>("VATPer")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.HasIndex("CurrencyID");

                    b.HasIndex("HotelID");

                    b.ToTable("Restaurant_OrderInfo", (string)null);
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.RestaurantOrderedProduct", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrderID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductID")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Rate")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("OrderID");

                    b.ToTable("RestaurantOrderedProduct", (string)null);
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.Room", b =>
                {
                    b.Property<string>("RoomNo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RoomCharges")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoomType")
                        .HasColumnType("TEXT");

                    b.HasKey("RoomNo");

                    b.ToTable("Room", (string)null);
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.Stock", b =>
                {
                    b.Property<string>("StockID")
                        .HasColumnType("TEXT");

                    b.Property<string>("LiquorName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("NoOfBottles")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StockDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TotalVolume")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Volume")
                        .HasColumnType("INTEGER");

                    b.HasKey("StockID");

                    b.HasIndex("LiquorName");

                    b.ToTable("Stock", (string)null);
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.StockBeer", b =>
                {
                    b.Property<string>("StockID")
                        .HasColumnType("TEXT");

                    b.Property<string>("BeerID")
                        .HasColumnType("TEXT");

                    b.Property<int?>("NoOfBottles")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StockDate")
                        .HasColumnType("TEXT");

                    b.HasKey("StockID");

                    b.HasIndex("BeerID");

                    b.ToTable("Stock_Beer", (string)null);
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.TaxInfo", b =>
                {
                    b.Property<string>("Salray")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TaxinP")
                        .HasColumnType("INTEGER")
                        .HasColumnName("taxinP");

                    b.HasKey("Salray");

                    b.ToTable("Taxinfo", (string)null);
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.TaxOrder", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("EducationalTax")
                        .HasColumnType("REAL");

                    b.Property<double?>("EducationalTaxAmount")
                        .HasColumnType("REAL");

                    b.Property<double?>("HEduTax")
                        .HasColumnType("REAL");

                    b.Property<double?>("HEduTaxAmount")
                        .HasColumnType("REAL");

                    b.Property<int?>("OrderID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("OrderID");

                    b.ToTable("Tax_order", (string)null);
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.TaxReservationHallAndGarden", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("EducationalTax")
                        .HasColumnType("REAL");

                    b.Property<double?>("EducationalTaxAmount")
                        .HasColumnType("REAL");

                    b.Property<double?>("HEduTax")
                        .HasColumnType("REAL");

                    b.Property<double?>("HEduTaxAmount")
                        .HasColumnType("REAL");

                    b.Property<string>("ReservationID")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("ReservationID");

                    b.ToTable("Tax_ReservationHallandGarden", (string)null);
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.TaxReservationHallOrGarden", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("EducationalTax")
                        .HasColumnType("REAL");

                    b.Property<double?>("EducationalTaxAmount")
                        .HasColumnType("REAL");

                    b.Property<double?>("HEduTax")
                        .HasColumnType("REAL");

                    b.Property<double?>("HEduTaxAmount")
                        .HasColumnType("REAL");

                    b.Property<string>("ReservationID")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("ReservationID");

                    b.ToTable("Tax_ReservationHallorGarden", (string)null);
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.TaxRestaurantOrder", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("EducationalTax")
                        .HasColumnType("REAL");

                    b.Property<double?>("EducationalTaxAmount")
                        .HasColumnType("REAL");

                    b.Property<double?>("HEduTax")
                        .HasColumnType("REAL");

                    b.Property<double?>("HEduTaxAmount")
                        .HasColumnType("REAL");

                    b.Property<int?>("OrderID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("OrderID");

                    b.ToTable("Tax_Restaurantorder", (string)null);
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.TaxRoom", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BillID")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("EducationalTax")
                        .HasColumnType("REAL");

                    b.Property<double?>("EducationalTaxAmount")
                        .HasColumnType("REAL");

                    b.Property<double?>("HEduTax")
                        .HasColumnType("REAL");

                    b.Property<double?>("HEduTaxAmount")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.HasIndex("BillID");

                    b.ToTable("Tax_Room", (string)null);
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.TempReservation", b =>
                {
                    b.Property<string>("ReservationID")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateIN")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOUT")
                        .HasColumnType("TEXT");

                    b.Property<string>("GuestID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("ReservationID");

                    b.HasIndex("GuestID");

                    b.HasIndex("RoomNo");

                    b.ToTable("Temp_Reservation", (string)null);
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.Trans", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AmountReceived")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DueAmount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Employee_Party_Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TransactionAmount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionDetails")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionMonth")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionType")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Trans", (string)null);
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Username");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.AdvanceEntry", b =>
                {
                    b.HasOne("HotelManager.Domain.Entities.EmployeeRegistration", "Employee")
                        .WithMany("Advances")
                        .HasForeignKey("EmployeeID");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.CheckInRoom", b =>
                {
                    b.HasOne("HotelManager.Domain.Entities.CurrencySet", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyID");

                    b.HasOne("HotelManager.Domain.Entities.Guest", "Guest")
                        .WithMany()
                        .HasForeignKey("GuestID");

                    b.HasOne("HotelManager.Domain.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomNo");

                    b.Navigation("Currency");

                    b.Navigation("Guest");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.CheckoutRoom", b =>
                {
                    b.HasOne("HotelManager.Domain.Entities.CheckInRoom", "CheckIn")
                        .WithMany("Checkouts")
                        .HasForeignKey("CheckInID");

                    b.HasOne("HotelManager.Domain.Entities.CurrencySet", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyID");

                    b.HasOne("HotelManager.Domain.Entities.HotelInfo", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelID");

                    b.Navigation("CheckIn");

                    b.Navigation("Currency");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.EmployeeAttendance", b =>
                {
                    b.HasOne("HotelManager.Domain.Entities.EmployeeRegistration", "Employee")
                        .WithMany("Attendances")
                        .HasForeignKey("EmployeeID");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.EmployeePayment", b =>
                {
                    b.HasOne("HotelManager.Domain.Entities.EmployeeRegistration", "Employee")
                        .WithMany("Payments")
                        .HasForeignKey("EmployeeID");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.Liquor", b =>
                {
                    b.HasOne("HotelManager.Domain.Entities.LiquorMaster", "Master")
                        .WithMany()
                        .HasForeignKey("LiquorName");

                    b.Navigation("Master");
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.OrderInfo", b =>
                {
                    b.HasOne("HotelManager.Domain.Entities.CheckInRoom", "CheckIn")
                        .WithMany("Orders")
                        .HasForeignKey("CheckInID");

                    b.HasOne("HotelManager.Domain.Entities.CurrencySet", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyID");

                    b.HasOne("HotelManager.Domain.Entities.HotelInfo", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelID");

                    b.Navigation("CheckIn");

                    b.Navigation("Currency");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.OrderedProduct", b =>
                {
                    b.HasOne("HotelManager.Domain.Entities.OrderInfo", "Order")
                        .WithMany("Products")
                        .HasForeignKey("OrderID");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("HotelManager.Domain.Entities.Guest", "Guest")
                        .WithMany()
                        .HasForeignKey("GuestID");

                    b.HasOne("HotelManager.Domain.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomNo");

                    b.Navigation("Guest");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.ReservationHallAndGarden", b =>
                {
                    b.HasOne("HotelManager.Domain.Entities.CurrencySet", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyID");

                    b.HasOne("HotelManager.Domain.Entities.Guest", "Guest")
                        .WithMany()
                        .HasForeignKey("GuestID");

                    b.HasOne("HotelManager.Domain.Entities.HotelInfo", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelID");

                    b.Navigation("Currency");

                    b.Navigation("Guest");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.ReservationHallOrGarden", b =>
                {
                    b.HasOne("HotelManager.Domain.Entities.CurrencySet", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyID");

                    b.HasOne("HotelManager.Domain.Entities.Guest", "Guest")
                        .WithMany()
                        .HasForeignKey("GuestID");

                    b.HasOne("HotelManager.Domain.Entities.HotelInfo", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelID");

                    b.Navigation("Currency");

                    b.Navigation("Guest");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.RestaurantOrderInfo", b =>
                {
                    b.HasOne("HotelManager.Domain.Entities.CurrencySet", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyID");

                    b.HasOne("HotelManager.Domain.Entities.HotelInfo", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelID");

                    b.Navigation("Currency");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.RestaurantOrderedProduct", b =>
                {
                    b.HasOne("HotelManager.Domain.Entities.RestaurantOrderInfo", "Order")
                        .WithMany("Products")
                        .HasForeignKey("OrderID");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.Stock", b =>
                {
                    b.HasOne("HotelManager.Domain.Entities.LiquorMaster", "LiquorMaster")
                        .WithMany()
                        .HasForeignKey("LiquorName");

                    b.Navigation("LiquorMaster");
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.StockBeer", b =>
                {
                    b.HasOne("HotelManager.Domain.Entities.Beer", "Beer")
                        .WithMany()
                        .HasForeignKey("BeerID");

                    b.Navigation("Beer");
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.TaxOrder", b =>
                {
                    b.HasOne("HotelManager.Domain.Entities.OrderInfo", "Order")
                        .WithMany("Taxes")
                        .HasForeignKey("OrderID");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.TaxReservationHallAndGarden", b =>
                {
                    b.HasOne("HotelManager.Domain.Entities.ReservationHallAndGarden", "Reservation")
                        .WithMany()
                        .HasForeignKey("ReservationID");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.TaxReservationHallOrGarden", b =>
                {
                    b.HasOne("HotelManager.Domain.Entities.ReservationHallOrGarden", "Reservation")
                        .WithMany()
                        .HasForeignKey("ReservationID");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.TaxRestaurantOrder", b =>
                {
                    b.HasOne("HotelManager.Domain.Entities.RestaurantOrderInfo", "Order")
                        .WithMany("Taxes")
                        .HasForeignKey("OrderID");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.TaxRoom", b =>
                {
                    b.HasOne("HotelManager.Domain.Entities.CheckoutRoom", "Bill")
                        .WithMany("Taxes")
                        .HasForeignKey("BillID");

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.TempReservation", b =>
                {
                    b.HasOne("HotelManager.Domain.Entities.Guest", "Guest")
                        .WithMany()
                        .HasForeignKey("GuestID");

                    b.HasOne("HotelManager.Domain.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomNo");

                    b.Navigation("Guest");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.User", b =>
                {
                    b.HasOne("HotelManager.Domain.Entities.Registration", "Registration")
                        .WithMany()
                        .HasForeignKey("Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.CheckInRoom", b =>
                {
                    b.Navigation("Checkouts");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.CheckoutRoom", b =>
                {
                    b.Navigation("Taxes");
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.EmployeeRegistration", b =>
                {
                    b.Navigation("Advances");

                    b.Navigation("Attendances");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.OrderInfo", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Taxes");
                });

            modelBuilder.Entity("HotelManager.Domain.Entities.RestaurantOrderInfo", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Taxes");
                });
#pragma warning restore 612, 618
        }
    }
}
